config/routes.rb
ProfoundInstallations::Application.routes.draw do

  devise_for :admins, :skip => [:registrations, :passwords] 

  as :admin do
    get "/admin" => "devise/sessions#new"
  end

  resources :cms, :only => [:create]
  resources :contact
  resources :gallery_uploads, :path => '/admin/gallery_uploads'
  resources :image_uploads, :only => [:destroy, :update, :create], :path => '/admin/image_uploads'
  resources :testimonials, :path => '/admin/testimonials'
  resources :about, :only => [:index, :edit, :update], :path => '/admin/about'

  root :to => 'home#index'

  match '/about' => 'home#about'
  match '/gallery' => 'home#gallery'
  match '/testimonials' => 'home#testimonials'
  match 'messagesent' => 'home#messagesent'

  # Gallery
  match '/gallery/:gallery_url' => 'home#gallery_album'

  # Admin dashboard
  match '/admin/dashboard' => 'dashboard#index'
  match '/admin/dashboard/gallery' => 'dashboard#gallery'

end

app/controllers/gallery_uploads_controller.rb
require 'fileutils'

class GalleryUploadsController < ApplicationController
  before_filter :authenticate_admin!
  layout 'dashboard', :only => [:index, :new, :edit]

  def index
    @albums = Album.all
  end

  def create
    images      = params[:file_upload][:my_files]
    album_title = params[:file_upload][:title]
    slug = album_title.downcase.strip.gsub(' ', '_').gsub(/[^\w-]/, '')
    album = Album.new(:title => album_title, :slug=>slug)
    if Image.check_images_are_valid(images) == true && album_title != ''
      album.save
      gallery_id = album.id
      directory_location = "#{APP_CONFIG[Rails.env]['upload_images_path']}/images/albums/#{slug}"
      FileUtils.mkdir directory_location
      Image.upload_images(images, directory_location, gallery_id)
      cover_image = Image.find_by_gallery_id(gallery_id).file_location
      album.update_attributes(:cover_image=>cover_image)
      redirect_to gallery_uploads_path, :notice => 'Successfully created album'
    else
      redirect_to gallery_uploads_path, :alert => 'Something went wrong. Album not saved.'
    end
  end

  def destroy
    id = params[:id]
    album = Album.find(id).destroy
    # Destroy all images that were inside this album.
    Image.where(gallery_id: id).destroy_all
    FileUtils.rm_rf("#{APP_CONFIG[Rails.env]['upload_images_path']}/images/albums/#{album.slug}")
    redirect_to gallery_uploads_path, :notice => 'Successfully deleted album'
  end

  # Update album title in database, including locations and changing directory name
  def update
    id = params[:id]
    album = Album.find(id)
    title = params[:title]
    old_slug = album.slug
    new_slug = title.downcase.strip.gsub(' ', '_').gsub(/[^\w-]/, '')
    new_cover_image = album.cover_image.gsub(old_slug,new_slug)
    album.update_attributes(:title=>title, :slug=>new_slug, :cover_image=>new_cover_image)
    Image.where(gallery_id: id).each do |image|
      new_file_location = image.file_location.gsub(old_slug,new_slug)
      image.update_attributes(:file_location=>new_file_location)
    end
    dir = "#{APP_CONFIG[Rails.env]['upload_images_path']}/images/albums/"
    FileUtils.mv("#{dir}#{old_slug}", "#{dir}#{new_slug}")
    redirect_to edit_gallery_upload_path(id)
  end

  def edit
    id = params[:id]
    @album = Album.find(id)
    @images = Image.where(:gallery_id=>id)
  end

end

app/helpers/gallery_uploads_helper.rb
module GalleryUploadsHelper
end

app/views/gallery_uploads/edit.html.erb
<% unless flash[:notice].blank? %>
  <div class="alert">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= content_tag :div, flash[:notice] %>
  </div>
<% end %>

<% unless flash[:alert].blank? %>
  <div class="alert">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= content_tag :div, flash[:alert] %>
  </div>
<% end %>


<div class='content'>
  <%= link_to '<< Back to all albums', gallery_uploads_path %>
  <h1 class='album_title'><%= @album.title %></h1>

  <%= form_tag(gallery_upload_path(params[:id]), :method => :put) do %>
    <%= label_tag 'title', 'Edit Album Title:' %>
    <%= text_field_tag 'title', @album.title %>
    <%= submit_tag 'Edit title', :class=>'btn btn-success', :id=>'contact_submit' %>
  <% end %>

  <h2>Add more images to this album...</h2>
  <div>
    <%= form_for :file_upload, :html => {:multipart => true, :id=>'gallery_upload'}, :url=>image_uploads_path(:gallery_id=>@album.id) do |f| %>
      <%= f.label :my_files, 'Choose the images you want to add to this album:' %>
      <%= f.file_field :my_files, :multiple=>true %><br />
      <%= f.submit "Upload", :class=>'btn btn-primary upload_button' %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="span img-polaroid-container">
    <h4>Cover Image</h4>
    <div class="img-polaroid">
      <%= image_tag("#{@album.cover_image}", :alt => @album.title) %>
    </div>
  </div>
</div>

<div class='row'>
  <% @images.each do |image| %>
    <div class="span2 img-polaroid-container">
      <div class="img-polaroid">
        <%= image_tag("#{image.file_location}", :alt => image.file_location.gsub(/.*\//,'').gsub(/\..*/,'')) %>
      </div>
        <%= button_to "Set as cover image", image_upload_path(:image_id=>image.id,:gallery_id=>image.gallery_id), 
              :method => :put, 
              :class=>'btn btn-success' %>
        <%= button_to "Delete Image", image_upload_path(image.id), 
                          :confirm => "Are you sure you want to delete this image?", 
                          :method => :delete, 
                          :class=>'btn btn-danger' %>
    </div>
  <% end %>
</div>

app/views/gallery_uploads/index.html.erb
<% unless flash[:notice].blank? %>
  <div class="alert">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= content_tag :div, flash[:notice] %>
  </div>
<% end %>

<% unless flash[:alert].blank? %>
  <div class="alert">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= content_tag :div, flash[:alert] %>
  </div>
<% end %>

<%= link_to '<< Back to dashboard', '/admin/dashboard' %>

<h3>Gallery Album Uploads</h3>

<ol>
  <li>Click add new album.</li>
  <li>Choose title and the images you want to upload.</li>
  <li>Click 'upload' button and your gallery will now be visible to the public.</li>
</ol>

<%= link_to 'Add new album', new_gallery_upload_path, :class=>'btn btn-warning btn-large add_new_album' %>
<div class="row">
  <% @albums.each do |album| %>  
      <div class="span img-polaroid-container">
        <div class="img-polaroid">
          <%= image_tag("#{album.cover_image}", :alt => album.title) %>
          <p><%= album.title %></p>
        </div>
        <%= button_to "Edit Album", edit_gallery_upload_path(album.id),
                                      :class=>'btn btn-success', 
                                      :method=>:get %>
        <%= button_to "Delete Album", gallery_upload_path(album.id), 
                                      :confirm => "Are you sure you want to delete this album?", 
                                      :method => :delete, 
                                      :class=>'btn btn-danger' %>
      </div>
  <% end %>
</div>

app/views/gallery_uploads/new.html.erb
<p><%= link_to '<< Back to all albums', gallery_uploads_path %></p>
<div class='content'>
  <h1>Gallery uploads</h1>

  <%= form_for :file_upload, :html => {:multipart => true, :id=>'gallery_upload'}, :url=>gallery_uploads_path do |f| %>
    <%= f.label :title, 'Title of album (e.g. \'Flat Roof\'):' %>
    <%= f.text_field :title %><br />
    <%= f.label :my_files, 'Choose the images you want to add to this album:' %>
    <%= f.file_field :my_files, :multiple=>true %><br />
    <%= f.submit "Upload", :class=>'btn btn-primary upload_button' %>
  <% end %>
</div>