config/routes.rb
ProfoundInstallations::Application.routes.draw do

  devise_for :admins, :skip => [:registrations, :passwords] 

  as :admin do
    get "/admin" => "devise/sessions#new"
  end

  resources :cms, :only => [:create]
  resources :contact
  resources :gallery_uploads, :path => '/admin/gallery_uploads'
  resources :image_uploads, :only => [:destroy, :update, :create], :path => '/admin/image_uploads'
  resources :testimonials, :path => '/admin/testimonials'
  resources :about, :only => [:index, :edit, :update], :path => '/admin/about'

  root :to => 'home#index'

  match '/about' => 'home#about'
  match '/gallery' => 'home#gallery'
  match '/testimonials' => 'home#testimonials'
  match 'messagesent' => 'home#messagesent'

  # Gallery
  match '/gallery/:gallery_url' => 'home#gallery_album'

  # Admin dashboard
  match '/admin/dashboard' => 'dashboard#index'
  match '/admin/dashboard/gallery' => 'dashboard#gallery'

end

app/models/about.rb
class About < ActiveRecord::Base
  attr_accessible :body
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  before_filter :authenticate_admin!
  layout 'dashboard'

  # GET
  def index
  	@about = About.first
  end

  # GET /about/:id/edit
  def edit
  	@about = About.first
  end

  # PUT
  def update
   	body = params[:body]
  	About.first.update_attributes(:body=> body)
  	redirect_to about_index_path, :notice => 'Successfully updated About page.'
  end
end

app/views/about/edit.html.erb
<h1>Edit About Page</h1>

<%= form_tag(about_path(1), :method => :put) do %>
  <%= label_tag :body %>
  <%= text_area_tag :body, @about.body, :class=> 'admin_about_text_area' %><br />
  <%= submit_tag %>
<% end %>

app/views/about/index.html.erb
<%= link_to '<< Back to dashboard', '/admin/dashboard' %>
<h1>About Page</h1>

<% unless flash[:notice].blank? %>
  <div class="alert">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= content_tag :div, flash[:notice] %>
  </div>
<% end %>

<p><%= sanitize(simple_format(@about.body), :tags => %w(br p) ) %></p>
<%= link_to 'edit', edit_about_path(1), :class=>'btn btn-success' %>