config/routes.rb
ProfoundInstallations::Application.routes.draw do

  devise_for :admins, :skip => [:registrations, :passwords] 

  as :admin do
    get "/admin" => "devise/sessions#new"
  end

  resources :cms, :only => [:create]
  resources :contact
  resources :gallery_uploads, :path => '/admin/gallery_uploads'
  resources :image_uploads, :only => [:destroy, :update, :create], :path => '/admin/image_uploads'
  resources :testimonials, :path => '/admin/testimonials'
  resources :about, :only => [:index, :edit, :update], :path => '/admin/about'

  root :to => 'home#index'

  match '/about' => 'home#about'
  match '/gallery' => 'home#gallery'
  match '/testimonials' => 'home#testimonials'
  match 'messagesent' => 'home#messagesent'

  # Gallery
  match '/gallery/:gallery_url' => 'home#gallery_album'

  # Admin dashboard
  match '/admin/dashboard' => 'dashboard#index'
  match '/admin/dashboard/gallery' => 'dashboard#gallery'

end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
  attr_accessible :body, :name

  validates_presence_of :body, :name
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  before_filter :authenticate_admin!

  layout 'dashboard', :only => [:index, :new, :edit]
  
  # GET /testimonials
  def index
  	@testimonials = Testimonial.all
  end

  # GET /testimonials/new
  def new
  end

  # GET /testimonials/:id/edit
  def edit
  	testimonial_id = params[:id]
  	@testimonial = Testimonial.find(testimonial_id)
  end

  # PUT /testimonials/:id
  def update
  	testimonial_id = params[:id]
  	new_name = params[:name]
  	new_body = params[:body]
  	testimonial = Testimonial.update( testimonial_id, :name=> new_name, :body => new_body )
  	if testimonial.save
      redirect_to testimonials_path, :notice => "Successfully updated testimonial."
  	else
      redirect_to testimonials_path, :alert => "Something went wrong. Did you include both a name and message?"
  	end
  end

  # POST /testimonials
  def create
  	name = params[:name]
  	body = params[:body]
  	testimonial = Testimonial.new(name: name, body: body)
  	if testimonial.save
      redirect_to testimonials_path, :notice => "Successfully added testimonial from #{name}."
    else
      redirect_to testimonials_path, :notice => "Something went wrong. Did you include both a name and message?"
  	end
  end

  # DELETE /testimonials/:id
  def destroy
  	testimonial_id = params[:id]
  	Testimonial.find(testimonial_id).destroy
  	redirect_to testimonials_path, :notice => 'Successfully deleted testimonial.'
  end

end

app/views/testimonials/edit.html.erb
<%= link_to '<< Back to testimonials', testimonials_path %>
<h1>Edit Testimonial</h1>

<%= form_tag(testimonial_path, :method=>'put') do %>
   <p>
    <%= label_tag "name", "Who said it?:" %>
    <%= text_field_tag "name", @testimonial.name %>
  </p>
  <p>
    <%= label_tag "body", "What did they say?:" %>
    <%= text_area_tag "body", @testimonial.body, :class=>'edit_testimonial_text_area' %>
  </p>
  <p>
    <%= submit_tag 'Submit' %>
  </p>
<% end %>

app/views/testimonials/index.html.erb
<% unless flash[:notice].blank? %>
  <div class="alert">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= content_tag :div, flash[:notice] %>
  </div>
<% end %>

<% unless flash[:alert].blank? %>
  <div class="alert">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= content_tag :div, flash[:alert] %>
  </div>
<% end %>

<%= link_to '<< Back to dashboard', '/admin/dashboard' %>

<h1>Testimonials</h1>

<%= link_to 'Add Testimonial', new_testimonial_path, :class=>'btn btn-warning add_new_testimonial' %>

<% @testimonials.each do |testimonial| %>
  <div class='admin_testimonial'>
  	<p><strong><%= testimonial.name %></strong></p>
    <p><%= sanitize(simple_format(testimonial.body), :tags => %w(br p) ) %></p>
    <%= link_to 'Edit', edit_testimonial_path(:id => testimonial.id) %> |
    <%= link_to 'Delete', testimonial_path(:id => testimonial.id), :method=> :delete, :confirm => 'Are you sure you want to delete this testimonial?' %>
  </div>
<% end %>

app/views/testimonials/new.html.erb
<h1>Create new testimonial</h1>

<%= form_tag(testimonials_path, :method=>'post') do %>
   <p>
    <%= label_tag "name", "Who said it?:" %>
    <%= text_field_tag "name" %>
  </p>
  <p>
    <%= label_tag "body", "What did they say?:" %>
    <%= text_area_tag "body", nil, :class=>'edit_testimonial_text_area' %>
  </p>
  <p>
    <%= submit_tag 'Submit' %>
  </p>
<% end %>